[book]
authors = ["Jho00"]
language = "ru"
multilingual = false
src = "src"
title = "Руководство по системной инженерии"

[build]
build-dir = "book"
create-missing = true

[preprocessor.drawio]
command = "mdbook-drawio"

[output.html]
additional-css = ["src/_assets/custom.css"]
additional-js = []
default-theme = "navy"
preferred-dark-theme = "navy"
